Changes: 23:42 delete is fixed!!! ============================================ ==              Run Results:              == ==  ==  ==  ==  ==  ==  ==  ==  ==  ==  ==== == Total Runs: 16 == Passed Runs: 14 == Failed Runs: 2 == Of which are exceptions: 1 == Exceptions occurred in cases:  9 == The following cases passed:  0 1 2 3 4 5 6 8 10 11 12 13 14 15 == The following cases failed:  7 The final score is: 90
need to fix:

java.lang.NullPointerException: Cannot invoke "AVLTree$IAVLNode.getHeight()" because the return value of "AVLTree$AVLNode.getRight()" is null
	at AVLTree$AVLNode.isLeaf(AVLTree.java:1413)
	at AVLTree.insert(AVLTree.java:161)
	at AVLTree.join(AVLTree.java:951)
	at AVLTree.split(AVLTree.java:902)
	at Tests.split(Tests.java:117)
	at ExTester$10.run(ExTester.java:321)
	at java.base/java.lang.Thread.run(Thread.java:833)